
- name: FTP Deployer
  uses: sand4rt/ftp-deployer@v1.7
  with:
    sftp: false # optional
    host: ${{ secrets.ftp_server }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
    port: 3000 # optional, default is: 21
    username: ${{ secrets.ftp_user }} # FTP username
    password: ${{ secrets.ftp_password }} # FTP password
    local_folder: dist # optional, local path, default is: dist
    cleanup: false # optional, remove existing files inside FTP remote folder
    exclude: '['node_modules', 'node_modules/**' '.git/**', '*.env']' # optional, e.g. '['node_modules/**', '.git/**', '*.env']'
    passive: true # optional